// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhohlkapexmeduaykggg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJob2hsa2FwZXhtZWR1YXlrZ2dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzIxNDUsImV4cCI6MjA2MjcwODE0NX0.v1nxr4k3-HZaUfiXzK3AqGeJnjP47WMexUuz-gbQsMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);